### ISSUE TITLE
人类的数值怎么来的？

### ISSUE THREAD

**Issue by So0ni** [CLUEbenchmark/SuperCLUE#15]
是把题目发在互联网上，然后从海量回答中选取最符合标准答案的回答吗？

**Comment by brightmart** [comment]
不是。由多个人来完成独立的做题，系统最后投票选取最终的答案。

**Comment by brightmart** [comment]
不是。由多个人来完成独立的做题，系统最后投票选取最终的答案。

**Comment by brightmart** [comment]
不是。由多个人来完成独立的做题，系统最后投票选取最终的答案。
