### ISSUE TITLE
阿里的通义千问没有吗？

### ISSUE THREAD

**Issue by Pancat009** [CLUEbenchmark/SuperCLUE#22]
测试有包含阿里的通义千问吗？

**Comment by better-one** [comment]
没有交钱上不了这个榜单的，再说了qwen如果上来了，百度怎么办，讯飞怎么办

**Comment by brightmart** [comment]
<img width="1296" alt="image" src="https://github.com/CLUEbenchmark/SuperCLUE/assets/19634224/4326449a-ca23-4bd2-8355-69eb868adb43">
最新的请再这里查看：https://www.superclueai.com/
