### ISSUE TITLE
Does it indicate using 5 shots for evaluation?

### ISSUE THREAD

**Issue by zhimin-z** [CLUEbenchmark/SuperCLUE#39]
![image](https://github.com/CLUEbenchmark/SuperCLUE/assets/8592144/cbd190c8-0029-4411-853c-cbfaa0daa890)
However, the original paper says zero-shot settings...for the leaderboard.
![image](https://github.com/CLUEbenchmark/SuperCLUE/assets/8592144/5c28fd15-d180-437c-b79b-514429698446)

**Comment by brightmart** [comment]
yes, zero-shot.
