### ISSUE TITLE
生成与创作如何用选择题的形式测试的？

### ISSUE THREAD

**Issue by Howardqlz** [CLUEbenchmark/SuperCLUE#5]
RT。很棒的工作！

**Comment by joytianya** [comment]
可以换个角度思考，强化学习reward model如何对模型生成评测的呢，是否可以转换成选择题呢，或许你就明白了

**Comment by Howardqlz** [comment]
> 可以换个角度思考，强化学习reward model如何对模型生成评测的呢，是否可以转换成选择题呢，或许你就明白了

按照你描述的，选择题的答案是待测模型生成的吗？然后使用评测模型进行选择？

**Comment by joytianya** [comment]
不是，只是为了说明选择题也可以从一定程度评测生成能力，更直观的生成评测后续会不断完善

**Comment by Howardqlz** [comment]
> 不是，只是为了说明选择题也可以从一定程度评测生成能力，更直观的生成评测后续会不断完善

OK那其实还是按照readme里说的都是选择题的形式。个人认为“reward model如何对模型生成评测”得不到“选择题也可以从一定程度评测生成能力”这个结论，因为reward model接收的答案是待评测模型生成的，而你们这里评测模型接收的答案是待评测模型生成的ABCD，还是很不一样的。
选择题的形式方便统计比较，但从提问的角度来看就把问题形式限定死了，实际上提问的方式可以有很多种。模型对提问形式的鲁棒性也很重要。
